# config.yml
theme:
  width: 400
  height: 100
  background: "#000000"
  pacman_color: "#FFDF00"
  dot_color: "#FFFFFF"
  ghost_colors:
    - "#FF6666"
    - "#66CCFF"
    - "#FFB86B"
    - "#BDBDFF"
layout:
  dot_count: 7
  dot_spacing: 50   # px
animation:
  duration_s: 5     # overall travel time (seconds) — only used for perceived speed in generator
  mouth_speed: 8    # higher = faster mouth open/close
update:
  stamp_label: true
